"""add owner

Revision ID: a8b986c331c6
Revises: 6e5bfd368eb4
Create Date: 2023-03-08 09:45:06.933827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b986c331c6'
down_revision = '6e5bfd368eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
